name: DEBUG BUILD macOS

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.cmake/**'
      - 'apps/**'
      - 'include/**'
      - 'src/**'
      - 'integration_tests/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install coverage
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j20
          make test
        env:
          CC: gcc-13
          CXX: g++-13